<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Research;
use App\Models\User;
use App\Models\College;
use App\Models\Category;

class ResearchSeeder extends Seeder
{
    public function run()
    {
        $students = User::where('role', 'student')->get();
        $approver = User::whereIn('role', ['super_admin', 'admin'])->orderBy('id')->first();
        $colleges = College::all();
        $categories = Category::all();

        $papers = [
            [
                'title' => 'Artificial Intelligence in Educational Technology: Enhancing Student Learning Outcomes',
                'college' => 'CICS',
                'abstract' => 'This study examines the integration of artificial intelligence tools in educational settings and their measurable impact on student learning outcomes across Philippine universities.',
                'introduction' => 'The rapid advancement of AI technology has created new opportunities for enhancing education. This study investigates how AI-powered tools can be effectively integrated into the Philippine educational system to improve student performance and engagement.',
                'methodology' => "A mixed-methods approach was employed, combining quantitative surveys of 500 students across 5 universities with qualitative interviews of 30 educators. Data was collected over two semesters using pre- and post-assessment scores.\n\nThe system development process used the Agile Model, as illustrated below:\n\n[figure: agile_model.png | Figure 1. Agile Development Model]\n\nThe Agile approach allowed for iterative development and continuous feedback from end-users throughout the research period.",
                'results' => "Students using AI-enhanced learning platforms showed significant improvements across all measured metrics. The following table summarizes the key findings:\n\n| Metric | Control Group | AI-Enhanced Group | Improvement |\n| Average Test Score | 72.4% | 89.1% | +23% |\n| Student Engagement | 58% | 78.3% | +35% |\n| Satisfaction Rating | 3.1/5.0 | 4.2/5.0 | +35% |\n| Assignment Completion | 71% | 88% | +24% |\n| Course Retention | 82% | 94% | +15% |\n\nThe overall assessment of the AI-enhanced platform using a 5-point Likert scale revealed high levels of acceptability across all dimensions:\n\n| Category | Mean | Descriptive Value |\n| Content Quality | 4.35 | Very High Extent |\n| System Usability | 4.12 | High Extent |\n| Learning Effectiveness | 4.28 | Very High Extent |\n| Technical Performance | 3.95 | High Extent |\n| Overall Mean | 4.18 | High Extent |",
                'discussion' => 'The findings suggest that AI integration significantly enhances learning outcomes when properly implemented. However, challenges remain in infrastructure, teacher training, and equitable access across urban and rural institutions.',
                'references' => "Baker, R. S., & Inventado, P. S. (2014). Educational data mining and learning analytics. In J. A. Larusson & B. White (Eds.), Learning analytics (pp. 61–75). Springer. https://doi.org/10.1007/978-1-4614-3305-7_4\nHolmes, W., Bialik, M., & Fadel, C. (2019). Artificial intelligence in education: Promises and implications for teaching and learning. Center for Curriculum Redesign.\nLuckin, R., Holmes, W., Griffiths, M., & Forcier, L. B. (2016). Intelligence unleashed: An argument for AI as a tool for teachers. Pearson Education.\nPopenici, S. A. D., & Kerr, S. (2017). Exploring the impact of artificial intelligence on teaching and learning in higher education. Research and Practice in Technology Enhanced Learning, 12(1), Article 22. https://doi.org/10.1186/s41039-017-0062-8\nZawacki-Richter, O., Marín, V. I., Bond, M., & Gouverneur, F. (2019). Systematic review of research on artificial intelligence applications in higher education. International Journal of Educational Technology in Higher Education, 16(1), Article 39.",
                'conclusion' => 'AI integration in educational technology significantly improves student learning outcomes when properly implemented with adequate infrastructure and teacher training. The 23% improvement in test scores and 35% increase in engagement demonstrate the transformative potential of AI-enhanced learning platforms in Philippine higher education.',
                'recommendations' => 'Universities should invest in AI-powered learning management systems and provide comprehensive training for educators. Government agencies should allocate funding for digital infrastructure in underserved institutions. Future research should explore long-term impacts of AI integration on student retention and career readiness.',
                'keywords' => 'artificial intelligence, educational technology, learning outcomes, EdTech, higher education, Philippines',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'Machine Learning Approaches for Predicting Academic Performance in Philippine Universities',
                'college' => 'CICS',
                'abstract' => 'This research develops and evaluates machine learning models for early prediction of student academic performance to enable timely interventions.',
                'introduction' => 'Academic performance prediction is critical for student retention. This study explores how machine learning algorithms can identify at-risk students early in the semester using enrollment and early assessment data.',
                'methodology' => 'Historical academic records of 10,000 students were analyzed using Random Forest, SVM, and Neural Network classifiers. Features included attendance, quiz scores, demographic data, and LMS activity logs.',
                'results' => "The Random Forest model achieved the highest accuracy among the three classifiers tested. The comparison of model performance is summarized below:\n\n| Model | Accuracy | Precision | Recall | F1-Score |\n| Random Forest | 87.2% | 85.6% | 88.1% | 86.8% |\n| SVM | 81.4% | 79.3% | 82.7% | 80.9% |\n| Neural Network | 84.7% | 83.2% | 85.9% | 84.5% |\n\nThe most influential features for predicting academic performance were identified through feature importance analysis:\n\n| Rank | Feature | Importance Score |\n| 1 | Early Quiz Scores (Weeks 1-4) | 0.312 |\n| 2 | LMS Login Frequency | 0.245 |\n| 3 | Attendance Rate | 0.198 |\n| 4 | Assignment Submission Timeliness | 0.127 |\n| 5 | Discussion Forum Participation | 0.068 |",
                'discussion' => 'Early prediction models can serve as effective early warning systems. The study recommends integrating these models into existing LMS platforms to provide automated alerts to advisers and students.',
                'references' => "Alamri, R., Alharbi, B., & Alshehri, M. (2021). Predicting student academic performance using machine learning: A systematic review. Education and Information Technologies, 26(4), 4067–4090. https://doi.org/10.1007/s10639-021-10498-x\nBreiman, L. (2001). Random forests. Machine Learning, 45(1), 5–32. https://doi.org/10.1023/A:1010933404324\nHellas, A., Ihantola, P., Petersen, A., Ajanovski, V. V., Gutica, M., Hynninen, T., & Liao, S. N. (2018). Predicting academic performance: A systematic literature review. Proceedings Companion of the 23rd Annual ACM Conference on Innovation and Technology in Computer Science Education, 175–199.\nRomero, C., & Ventura, S. (2020). Educational data mining and learning analytics: An updated survey. WIREs Data Mining and Knowledge Discovery, 10(3), Article e1355.",
                'conclusion' => 'Machine learning models, particularly Random Forest, can effectively predict student academic performance with 87% accuracy using early-semester data. These models serve as reliable early warning systems for identifying at-risk students.',
                'recommendations' => 'Educational institutions should integrate predictive analytics into their LMS platforms. Academic advisers should receive training on interpreting model outputs. Future studies should explore ensemble methods and incorporate socioeconomic factors for improved prediction accuracy.',
                'keywords' => 'machine learning, academic performance, prediction, Random Forest, early warning, student retention',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'Effectiveness of Online Learning Platforms During the COVID-19 Pandemic in Rural Areas',
                'college' => 'CTED',
                'abstract' => 'This study evaluates the effectiveness of online learning platforms adopted during the COVID-19 pandemic in rural Philippine communities.',
                'introduction' => 'The sudden shift to online learning during COVID-19 exposed digital divides, particularly in rural areas. This research examines how effectively online platforms served students in underserved communities.',
                'methodology' => 'Survey data was collected from 800 students and 120 teachers across 15 rural schools. Internet connectivity tests, device availability audits, and academic performance comparisons were conducted.',
                'results' => 'Only 42% of rural students had reliable internet access. Academic performance dropped by an average of 15% compared to pre-pandemic levels. Asynchronous learning modules were more effective than synchronous sessions.',
                'discussion' => 'The digital divide significantly impacted rural education during the pandemic. Recommendations include investing in community internet infrastructure, distributing devices, and developing offline-capable learning materials.',
                'references' => "Adnan, M., & Anwar, K. (2020). Online learning amid the COVID-19 pandemic: Students' perspectives. Journal of Pedagogical Sociology and Psychology, 2(1), 45–51. https://doi.org/10.33902/JPSP.2020261309\nBozkurt, A., & Sharma, R. C. (2020). Emergency remote teaching in a time of global crisis due to coronavirus pandemic. Asian Journal of Distance Education, 15(1), i–vi.\nToquero, C. M. (2020). Challenges and opportunities for higher education amid the COVID-19 pandemic: The Philippine context. Pedagogical Research, 5(4), Article em0063. https://doi.org/10.29333/pr/7947\nWorld Bank. (2020). Remote learning and COVID-19: The use of educational technologies at scale across an education system. World Bank Group.",
                'conclusion' => 'Online learning platforms were significantly less effective in rural areas due to the digital divide, with only 42% of students having reliable internet access. Asynchronous learning proved more practical than synchronous sessions in low-connectivity environments.',
                'recommendations' => 'Government should invest in community internet infrastructure for rural areas. Schools should develop offline-capable learning materials and provide devices to underserved students. Teacher training programs should include digital pedagogy for blended learning approaches.',
                'keywords' => 'online learning, COVID-19, rural education, digital divide, asynchronous learning, Philippines',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'Financial Literacy and Its Impact on Personal Investment Decisions Among College Students',
                'college' => 'CBEA',
                'abstract' => 'This research investigates the relationship between financial literacy levels and personal investment behavior among Filipino college students.',
                'introduction' => 'Financial literacy is essential for making informed investment decisions. With increasing access to digital investment platforms, understanding how financial education influences student investment behavior is crucial.',
                'methodology' => 'A cross-sectional survey of 600 college students was conducted using a validated financial literacy questionnaire. Investment behavior was measured through self-reported portfolio data and investment frequency.',
                'results' => 'Students with high financial literacy scores were 3 times more likely to invest regularly. 65% of financially literate students diversified their investments, compared to only 20% of those with low literacy.',
                'discussion' => 'Integrating comprehensive financial literacy programs into college curricula could significantly improve student investment readiness. The study recommends mandatory personal finance courses across all degree programs.',
                'references' => "Lusardi, A., & Mitchell, O. S. (2014). The economic importance of financial literacy: Theory and evidence. Journal of Economic Literature, 52(1), 5–44. https://doi.org/10.1257/jel.52.1.5\nMangundayao, I. T., & Garcia, R. P. (2021). Financial literacy among Filipino college students: A basis for financial education program. International Journal of Business and Management, 16(5), 34–48.\nOECD. (2020). PISA 2018 results (Volume IV): Are students smart about money? OECD Publishing. https://doi.org/10.1787/48ebd1ba-en\nRooij, M. C., Lusardi, A., & Alessie, R. J. (2011). Financial literacy and stock market participation. Journal of Financial Economics, 101(2), 449–472. https://doi.org/10.1016/j.jfineco.2011.03.006",
                'conclusion' => 'Financial literacy has a strong positive correlation with investment behavior among Filipino college students. Financially literate students are three times more likely to invest regularly and demonstrate better portfolio diversification.',
                'recommendations' => 'CHED should mandate personal finance courses across all degree programs. Universities should partner with financial institutions to provide practical investment workshops. Future research should track the long-term financial outcomes of students who received financial literacy education.',
                'keywords' => 'financial literacy, investment behavior, college students, personal finance, portfolio diversification',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'Aquaculture Innovation: Sustainable Fish Farming Practices in Laguna de Bay',
                'college' => 'CFAS',
                'abstract' => 'This study evaluates innovative and sustainable aquaculture practices being implemented in Laguna de Bay to balance economic productivity with environmental conservation.',
                'introduction' => 'Laguna de Bay is the largest lake in the Philippines and a critical aquaculture zone. Environmental degradation threatens both the ecosystem and the livelihoods of thousands of fish farmers.',
                'methodology' => 'Field studies were conducted across 25 fish farms over 12 months. Water quality parameters, fish yield data, and economic metrics were compared between traditional and sustainable farming methods.',
                'results' => 'Sustainable practices reduced water pollution by 40% while maintaining 92% of traditional yield levels. Feed conversion ratios improved by 18% using locally-sourced organic feeds.',
                'discussion' => 'Sustainable aquaculture is economically viable in Laguna de Bay. Policy support and farmer education programs are needed to accelerate adoption of environmentally responsible practices.',
                'references' => "Béné, C., Arthur, R., & Norbert, H. (2016). Contribution of fisheries and aquaculture to food security. World Development, 79, 177–196. https://doi.org/10.1016/j.worlddev.2015.11.007\nEdwards, P. (2015). Aquaculture environment interactions: Past, present and likely future trends. Aquaculture, 447, 2–14. https://doi.org/10.1016/j.aquaculture.2015.02.001\nNaylor, R. L., Hardy, R. W., Buschmann, A. H., & Bush, S. R. (2021). A 20-year retrospective review of global aquaculture. Nature, 591(7851), 551–563. https://doi.org/10.1038/s41586-021-03308-6",
                'conclusion' => 'Sustainable aquaculture practices in Laguna de Bay are economically viable, reducing water pollution by 40% while maintaining 92% of traditional yield levels. Organic feed alternatives improved feed conversion ratios by 18%.',
                'recommendations' => 'BFAR should create incentive programs for fish farmers adopting sustainable practices. Local government units should enforce water quality standards. Research institutions should develop region-specific organic feed formulations to further reduce costs.',
                'keywords' => 'aquaculture, sustainable fish farming, Laguna de Bay, water quality, organic feeds, Philippines',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'Renewable Energy Integration in Industrial Manufacturing Processes',
                'college' => 'CIT',
                'abstract' => 'This research examines the feasibility and impact of integrating renewable energy sources into Philippine industrial manufacturing operations.',
                'introduction' => 'The Philippines relies heavily on fossil fuels for industrial energy. This study explores how solar, wind, and biomass energy can be integrated into manufacturing to reduce costs and carbon emissions.',
                'methodology' => 'Energy audits were conducted at 15 manufacturing facilities. Simulation models were developed to project the impact of renewable energy integration on operational costs and emissions over 10 years.',
                'results' => 'Solar panel integration could reduce energy costs by 30% within 5 years. Combined renewable sources could decrease carbon emissions by 45%. Initial investment payback period averaged 3.5 years.',
                'discussion' => 'Renewable energy integration is both environmentally and economically beneficial for Philippine manufacturers. Government incentives and financing programs could accelerate adoption across the industrial sector.',
                'references' => "IRENA. (2020). Renewable energy and jobs: Annual review 2020. International Renewable Energy Agency.\nLund, H. (2014). Renewable energy systems: A smart energy systems approach to the choice and modeling of 100% renewable solutions (2nd ed.). Academic Press.\nOwusu, P. A., & Asumadu-Sarkodie, S. (2016). A review of renewable energy sources, sustainability issues and climate change mitigation. Cogent Engineering, 3(1), Article 1167990. https://doi.org/10.1080/23311916.2016.1167990",
                'conclusion' => 'Renewable energy integration in Philippine manufacturing is both environmentally and economically beneficial, with solar panels reducing energy costs by 30% and combined renewable sources decreasing carbon emissions by 45%.',
                'recommendations' => 'The government should expand renewable energy incentives for manufacturing. Industry associations should facilitate knowledge sharing among early adopters. Future research should explore energy storage solutions to address intermittency challenges in tropical climates.',
                'keywords' => 'renewable energy, solar power, manufacturing, carbon emissions, industrial sustainability, Philippines',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'Community-Based Crime Prevention Strategies in Urban Barangays',
                'college' => 'CCJE',
                'abstract' => 'This study analyzes the effectiveness of community-based crime prevention programs implemented in urban barangays in Metro Manila.',
                'introduction' => 'Community-based approaches to crime prevention emphasize local participation and social cohesion. This research evaluates various community programs and their impact on crime rates in urban barangays.',
                'methodology' => 'A comparative study of 20 barangays was conducted, analyzing crime statistics, community program participation rates, and resident perception surveys over a 3-year period.',
                'results' => 'Barangays with active community watch programs saw a 28% reduction in property crimes. Youth engagement programs reduced juvenile delinquency by 35%. Community satisfaction with safety increased by 40%.',
                'discussion' => 'Community-based programs are effective supplements to traditional policing. Success depends on sustained community engagement, local government support, and adequate resource allocation.',
                'references' => "Lab, S. P. (2020). Crime prevention: Approaches, practices, and evaluations (10th ed.). Routledge.\nTilley, N. (2009). Crime prevention. Willan Publishing.\nWeisburd, D., & Eck, J. E. (2004). What can police do to reduce crime, disorder, and fear? The Annals of the American Academy of Political and Social Science, 593(1), 42–65. https://doi.org/10.1177/0002716203262548\nWelsh, B. C., & Farrington, D. P. (2012). The Oxford handbook of crime prevention. Oxford University Press.",
                'conclusion' => 'Community-based crime prevention programs effectively reduce property crimes by 28% and juvenile delinquency by 35% in urban barangays. Community watch programs and youth engagement initiatives are the most impactful interventions.',
                'recommendations' => 'LGUs should allocate dedicated funding for community-based crime prevention programs. PNP should formalize partnerships with barangay watch groups. DILG should develop standardized training modules for community volunteers and expand youth mentorship programs.',
                'keywords' => 'crime prevention, community watch, barangay, juvenile delinquency, Metro Manila, urban safety',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'Medicinal Plant Utilization Among Indigenous Communities in Mindanao',
                'college' => 'CHM',
                'abstract' => 'This research documents and scientifically evaluates traditional medicinal plant practices among indigenous communities in Mindanao.',
                'introduction' => 'Indigenous communities in Mindanao possess rich traditional knowledge of medicinal plants. This study aims to document these practices and evaluate the pharmacological properties of commonly used plants.',
                'methodology' => 'Ethnobotanical surveys were conducted with 150 traditional healers across 8 indigenous communities. 45 plant species were collected and subjected to phytochemical screening and antimicrobial assays.',
                'results' => '32 of 45 tested plants showed significant antimicrobial activity. 12 plants contained novel alkaloid compounds not previously documented. Traditional dosage practices were found to be within safe therapeutic ranges.',
                'discussion' => 'The indigenous medicinal plant knowledge represents a valuable resource for pharmaceutical research. Conservation of these plant species and protection of indigenous intellectual property rights are critical priorities.',
                'references' => "Balick, M. J., & Cox, P. A. (2020). Plants, people, and culture: The science of ethnobotany (2nd ed.). Garland Science.\nFarnsworth, N. R., & Soejarto, D. D. (1991). Global importance of medicinal plants. In O. Akerele, V. Heywood, & H. Synge (Eds.), The conservation of medicinal plants (pp. 25–51). Cambridge University Press.\nNewman, D. J., & Cragg, G. M. (2020). Natural products as sources of new drugs over the nearly four decades from 01/1981 to 09/2019. Journal of Natural Products, 83(3), 770–803. https://doi.org/10.1021/acs.jnatprod.9b01285",
                'conclusion' => 'Indigenous medicinal plant knowledge in Mindanao is scientifically validated, with 32 of 45 tested plants showing significant antimicrobial activity and 12 containing novel alkaloid compounds. Traditional dosage practices fall within safe therapeutic ranges.',
                'recommendations' => 'DENR should prioritize conservation of identified medicinal plant species. DOST should fund further pharmacological studies on the 12 novel alkaloid compounds. NCIP should help establish intellectual property protections for indigenous traditional knowledge holders.',
                'keywords' => 'ethnobotany, medicinal plants, indigenous communities, antimicrobial, Mindanao, phytochemistry',
                'status' => Research::STATUS_APPROVED,
            ],

            // --- Additional papers with varied abstracts and statuses ---

            [
                'title' => 'Blockchain Technology for Secure and Transparent Academic Record Management',
                'college' => 'CICS',
                'abstract' => 'This paper proposes a blockchain-based system for managing academic records in Philippine higher education institutions, addressing concerns of document forgery, data integrity, and verification inefficiency. The system leverages decentralized ledger technology to provide tamper-proof credential storage and instant verifiability for employers and graduate schools.',
                'introduction' => 'Academic credential fraud is a growing problem in the Philippines, with cases of falsified transcripts and bogus diplomas reported across industries. This research presents a blockchain architecture tailored for Philippine HEIs to issue, store, and verify academic records securely and transparently.',
                'methodology' => 'A prototype blockchain system was developed using Hyperledger Fabric. The system was pilot-tested with 3 partner universities over one semester, processing 2,400 credential issuances. Performance benchmarks measured transaction throughput, verification latency, and system uptime.',
                'results' => "The prototype achieved 99.97% system uptime and processed credential verifications in under 2 seconds. Benchmark results for the blockchain system versus traditional record management:\n\n| Metric | Traditional System | Blockchain System |\n| Verification Time | 3–5 business days | 1.8 seconds |\n| Document Forgery Risk | High | Near-zero |\n| Storage Cost (per record) | PHP 120 | PHP 18 |\n| Audit Trail Availability | Manual | Automatic |",
                'discussion' => 'The blockchain approach eliminates single points of failure inherent in centralized databases. Stakeholders including employers and government agencies responded positively to the instant verification feature, citing a 90% reduction in processing time for credential checks.',
                'references' => "Grech, A., & Camilleri, A. F. (2017). Blockchain in education. Publications Office of the European Union. https://doi.org/10.2760/60649\nJu, Y., Kim, J., & Ahn, K. (2020). Blockchain-based academic credential verification system. Journal of Internet Computing and Services, 21(1), 23–30.\nSatoshi, N. (2008). Bitcoin: A peer-to-peer electronic cash system. https://bitcoin.org/bitcoin.pdf\nSullivan, C., & Burger, E. (2017). E-residency and blockchain. Computer Law & Security Review, 33(4), 470–481.",
                'conclusion' => 'Blockchain technology provides a practical, cost-effective solution for academic record management, reducing verification time from days to under 2 seconds and virtually eliminating document forgery risks.',
                'recommendations' => 'CHED should establish a national blockchain credential framework. HEIs should pilot decentralized identity solutions alongside existing student information systems. Future work should address interoperability standards across institutions.',
                'keywords' => 'blockchain, academic records, credential verification, Hyperledger, data integrity, higher education',
                'status' => Research::STATUS_PENDING_RDE,
            ],
            [
                'title' => 'IoT-Based Smart Campus Energy Monitoring and Optimization System',
                'college' => 'CICS',
                'abstract' => 'This study designs and implements an Internet of Things (IoT) framework for real-time energy consumption monitoring and automated optimization across university campus buildings. The proposed system integrates smart sensors, edge computing nodes, and a cloud-based analytics dashboard to identify energy waste patterns and trigger automated load-shedding responses.',
                'introduction' => 'Philippine universities spend a significant portion of their operational budgets on electricity. Smart building technologies offer a path to substantial savings. This research develops an IoT-driven solution adapted to the infrastructure constraints common in Philippine academic institutions.',
                'methodology' => 'Raspberry Pi-based sensor nodes were deployed across 12 campus buildings to measure power consumption at 5-minute intervals. Data was transmitted to a cloud dashboard via MQTT protocol. A rule-based automation engine was configured to control lighting and HVAC based on occupancy and time-of-day schedules.',
                'results' => 'Monthly energy consumption decreased by 22% after system deployment. Occupancy-triggered lighting controls contributed the largest savings at 38% reduction in lighting costs. The payback period for hardware investment was estimated at 14 months.',
                'discussion' => 'The low-cost IoT architecture proved reliable in a tropical campus environment with intermittent connectivity. The automation engine successfully prevented energy waste during unoccupied periods without user intervention.',
                'references' => "Gubbi, J., Buyya, R., Marusic, S., & Palaniswami, M. (2013). Internet of Things (IoT): A vision, architectural elements, and future directions. Future Generation Computer Systems, 29(7), 1645–1660.\nMiorandi, D., Sicari, S., De Pellegrini, F., & Chlamtac, I. (2012). Internet of things: Vision, applications and research challenges. Ad Hoc Networks, 10(7), 1497–1516.\nPasolini, G., Buratti, C., Feltrin, L., Zabini, F., De Castro, C., Verdone, R., & Andrisano, O. (2018). Smart city pilot projects using LoRa and IEEE802.15.4 technologies. Sensors, 18(4), Article 1118.",
                'conclusion' => 'The IoT-based smart campus system achieved a 22% reduction in energy consumption with a 14-month hardware payback period, demonstrating strong economic and environmental viability for Philippine universities.',
                'recommendations' => 'Universities should prioritize IoT retrofits in high-consumption buildings. Campus facility teams need training on dashboard interpretation. Future iterations should incorporate machine learning for predictive load forecasting.',
                'keywords' => 'IoT, smart campus, energy monitoring, Raspberry Pi, automation, sustainability',
                'status' => Research::STATUS_PENDING_COLLEGE,
            ],
            [
                'title' => 'Differentiated Instruction Strategies and Their Effect on Diverse Learner Achievement',
                'college' => 'CTED',
                'abstract' => 'This action research investigates how differentiated instruction (DI) strategies affect academic achievement across diverse learner profiles in Philippine senior high school classrooms. Through systematic variation of content, process, and product modalities, the study measures outcome differences among visual, auditory, and kinesthetic learners in mixed-ability classrooms.',
                'introduction' => 'Philippine classrooms are characterized by significant diversity in learning styles, linguistic backgrounds, and academic readiness. The K-12 curriculum mandates inclusive education yet provides limited guidance on DI implementation. This study fills that gap by documenting practical DI approaches and their measured impact.',
                'methodology' => 'A quasi-experimental design was employed with 4 Grade 11 classes (n=160) across 2 schools. Two classes received DI treatment while two served as controls with traditional whole-class instruction over one semester. Pre- and post-tests, learning style inventories, and classroom observation rubrics were used.',
                'results' => 'DI classrooms showed statistically significant improvement (p<0.05) across all learner profiles. Visual learners improved most (+27%), followed by kinesthetic (+22%) and auditory (+19%) learners. The achievement gap between high- and low-performing students narrowed by 31% in DI classrooms versus 8% in control classrooms.',
                'discussion' => 'DI is demonstrably effective in reducing achievement gaps in Philippine SHS classrooms. However, it requires substantially more preparation time from teachers, suggesting the need for curriculum-embedded planning tools.',
                'references' => "Subban, P. (2006). Differentiated instruction: A research basis. International Education Journal, 7(7), 935–947.\nTomlinson, C. A. (2014). The differentiated classroom: Responding to the needs of all learners (2nd ed.). ASCD.\nVygotsky, L. S. (1978). Mind in society: The development of higher psychological processes. Harvard University Press.\nWatson, K. L. (2017). Differentiated instruction and its effect on student achievement in junior high school mathematics. Walden Dissertations.",
                'conclusion' => 'Differentiated instruction significantly improves learning outcomes across all learner profiles and narrows the achievement gap by 31% compared to 8% in traditional classrooms, making it a high-impact strategy for Philippine senior high school.',
                'recommendations' => 'DepEd should embed differentiated instruction modules into teacher professional development. School heads should allocate joint planning time for DI lesson design. Future research should examine DI effectiveness in multigrade rural classrooms.',
                'keywords' => 'differentiated instruction, learning styles, senior high school, achievement gap, inclusive education',
                'status' => Research::STATUS_REVISION_COLLEGE,
                'revision_notes' => 'Please clarify the statistical tests used and provide the full test results table. The methodology section needs more detail on how learner profiles were validated.',
            ],
            [
                'title' => 'Values Education Integration in the K-12 Curriculum: Teacher Perspectives and Practices',
                'college' => 'CTED',
                'abstract' => 'This qualitative study explores how K-12 teachers perceive and implement values education integration across subject areas in Philippine public schools, identifying enablers, barriers, and best practices from classroom practitioners.',
                'introduction' => 'The K-12 Basic Education Program emphasizes values formation as a cross-cutting concern across all learning areas. Despite policy mandates, implementation is inconsistent. This research documents teacher perspectives and classroom practices to inform curriculum policy.',
                'methodology' => 'Phenomenological inquiry was conducted with 24 public school teachers from 3 provinces using in-depth interviews and classroom observations. Thematic analysis was applied to transcripts following Braun and Clarke\'s (2006) framework.',
                'results' => 'Three major themes emerged: (1) values education as an "invisible curriculum" embedded in teacher modeling, (2) assessment challenges due to the intangible nature of values, and (3) tension between standardized testing pressure and values formation time.',
                'discussion' => 'Teachers generally value values education but struggle to assess and document it formally. The hidden curriculum—teacher behavior and classroom culture—was identified as the most powerful vehicle for values transmission.',
                'references' => "Braun, V., & Clarke, V. (2006). Using thematic analysis in psychology. Qualitative Research in Psychology, 3(2), 77–101.\nKirschenbaum, H. (2000). From values clarification to character education: A personal journey. Journal of Humanistic Counseling, 39(1), 4–20.\nLickona, T. (1991). Educating for character: How our schools can teach respect and responsibility. Bantam Books.\nVillegas-Reimers, E. (2003). Teacher professional development: An international review of the literature. UNESCO International Institute for Educational Planning.",
                'conclusion' => 'Values education in K-12 is primarily enacted through teacher modeling and classroom culture rather than explicit instruction. The absence of practical assessment tools remains the most significant barrier to systematic implementation.',
                'recommendations' => 'DepEd should develop observable values assessment rubrics usable across subject areas. Pre-service teacher education should include practicum units specifically on values integration techniques.',
                'keywords' => 'values education, K-12 curriculum, teacher perspectives, character formation, qualitative research',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'Microfinance Program Participation and Economic Empowerment of Rural Women in Quezon Province',
                'college' => 'CBEA',
                'abstract' => 'This study examines the socioeconomic outcomes of microfinance program participation among rural women in Quezon Province, measuring changes in household income, asset ownership, financial autonomy, and self-efficacy over a two-year period.',
                'introduction' => 'Microfinance has been promoted as a development tool for poverty alleviation in the Philippines. This research critically examines whether microfinance participation translates into measurable economic empowerment for rural women, or whether debt burdens offset gains.',
                'methodology' => 'A longitudinal survey design tracked 320 female microfinance borrowers and 160 non-borrowers (control) across 10 rural municipalities in Quezon Province from 2022 to 2024. Difference-in-differences analysis was applied to isolate program effects.',
                'results' => 'Microfinance participants showed a 34% increase in household income and a 28% increase in productive asset ownership compared to controls. However, 22% of participants reported high financial stress from repayment obligations, and drop-out rates among the poorest borrowers were 19%.',
                'discussion' => 'Microfinance is effective for moderately poor households with existing business capacity but shows limited impact for the ultra-poor. Program design modifications emphasizing financial literacy and flexible repayment terms could improve outcomes.',
                'references' => "Banerjee, A., Duflo, E., Glennerster, R., & Kinnan, C. (2015). The miracle of microfinance? Evidence from a randomized evaluation. American Economic Journal: Applied Economics, 7(1), 22–53.\nBateman, M. (2010). Why doesn't microfinance work? The destructive rise of local neoliberalism. Zed Books.\nGonzalez-Vega, C. (2011). Microfinance: Broadening access to financial services. Ohio State University AED Economics.\nYunus, M. (2007). Creating a world without poverty: Social business and the future of capitalism. PublicAffairs.",
                'conclusion' => 'Microfinance participation yields significant income and asset gains for rural women but carries financial stress risks for the most vulnerable borrowers. Program design must be differentiated by poverty depth to maximize positive outcomes.',
                'recommendations' => 'MFIs should integrate financial literacy modules into loan onboarding. Regulatory bodies should mandate flexible repayment options for ultra-poor borrowers. Future research should track children\'s educational outcomes as an indirect measure of household economic improvement.',
                'keywords' => 'microfinance, rural women, economic empowerment, Quezon Province, poverty alleviation, household income',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'E-Commerce Adoption Barriers and Enablers Among Micro and Small Enterprises in Batangas',
                'college' => 'CBEA',
                'abstract' => 'This study identifies the key barriers and enablers of e-commerce adoption among micro and small enterprises (MSEs) in Batangas City, using the Technology Acceptance Model (TAM) as a theoretical lens to analyze owner attitudes, perceived usefulness, and adoption intentions.',
                'introduction' => 'Digital commerce offers significant growth opportunities for Philippine MSEs, yet adoption rates remain low. Understanding the specific barriers faced by small business owners in provincial settings is essential for crafting effective digital inclusion policies.',
                'methodology' => 'A structured survey of 280 MSE owners in Batangas City was conducted, supplemented by 20 semi-structured interviews. Structural equation modeling (SEM) was applied to test the TAM constructs and identify significant predictors of adoption intention.',
                'results' => 'Perceived ease of use (β=0.42, p<0.001) and perceived usefulness (β=0.38, p<0.001) were the strongest predictors of adoption intention. Trust concerns were the most cited barrier (68%), followed by lack of digital skills (54%) and logistics challenges (47%).',
                'discussion' => 'The TAM model effectively predicts e-commerce adoption intentions among MSE owners. Trust-building interventions—such as government-backed digital certification programs—could be the highest-leverage policy lever for increasing adoption.',
                'references' => "Davis, F. D. (1989). Perceived usefulness, perceived ease of use, and user acceptance of information technology. MIS Quarterly, 13(3), 319–340.\nLian, J. W., & Yen, D. C. (2014). Online shopping drivers and barriers for older adults. Computers in Human Behavior, 37, 133–143.\nPavlou, P. A., & Fygenson, M. (2006). Understanding and predicting electronic commerce adoption. MIS Quarterly, 30(1), 115–143.",
                'conclusion' => 'Trust and digital skill gaps are the primary barriers to e-commerce adoption among MSEs in Batangas. TAM constructs of perceived ease of use and usefulness significantly predict adoption intention.',
                'recommendations' => 'DTI should expand digital literacy programs specifically targeting MSE owners. E-marketplace platforms should simplify onboarding processes and provide local-language support. Future research should track actual adoption behavior beyond intention.',
                'keywords' => 'e-commerce, MSE, Technology Acceptance Model, Batangas, digital adoption, small business',
                'status' => Research::STATUS_PENDING_RDE,
            ],
            [
                'title' => 'Community-Led Mangrove Reforestation and Its Impact on Coastal Biodiversity in Quezon Province',
                'college' => 'CFAS',
                'abstract' => 'This study evaluates a five-year community-led mangrove reforestation program along the coastline of Quezon Province, assessing survival rates, biodiversity recovery, and socioeconomic benefits to coastal fisherfolk communities.',
                'introduction' => 'Mangrove deforestation in the Philippines has severely degraded coastal fisheries and increased vulnerability to storm surges. Community-based reforestation programs have emerged as a cost-effective conservation strategy, but rigorous evaluations of long-term outcomes are scarce.',
                'methodology' => 'Vegetation surveys, fish biomass assessments, and macroinvertebrate counts were conducted annually across 120 hectares of reforested sites and 40 hectares of control (non-reforested) sites. Household economic surveys captured income changes for 200 fishing families.',
                'results' => 'Planted mangrove stands achieved 74% survival rate after five years. Fish biomass in reforested areas increased by 56% compared to a 3% increase in control areas. Coastal fisherfolk reported a 29% average increase in daily catch income attributable to improved nursery habitat.',
                'discussion' => 'Community ownership of reforestation sites was the strongest predictor of high survival rates. Sites where communities had formal stewardship agreements showed 89% survival versus 61% for externally managed sites.',
                'references' => "Barbier, E. B. (2016). The protective service of mangrove ecosystems: A review of valuation methods. Marine Pollution Bulletin, 109(2), 676–681.\nDuke, N. C., Meynecke, J. O., Dittmann, S., & Ellison, A. M. (2007). A world without mangroves? Science, 317(5834), 41–42.\nLalacuna, R. C., & Evangelista, M. B. (2019). Community-based mangrove management in the Philippines: Lessons and challenges. Ocean & Coastal Management, 176, 100–112.",
                'conclusion' => 'Community-led mangrove reforestation achieves significantly higher survival rates and greater biodiversity recovery than externally managed programs. Formal stewardship agreements are the critical factor distinguishing high-performing sites.',
                'recommendations' => 'DENR should institutionalize community stewardship agreements as the standard model for mangrove reforestation projects. BFAR should integrate mangrove corridor mapping into fisheries management plans. LGUs should provide livelihood assistance to communities during the early non-productive years of reforestation.',
                'keywords' => 'mangrove reforestation, coastal biodiversity, fisherfolk, Quezon Province, community-based conservation',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => '3D Printing Applications in Low-Cost Housing Construction: A Philippine Context',
                'college' => 'CIT',
                'abstract' => 'This feasibility study investigates the potential of additive manufacturing (3D printing) technology to address the housing backlog in the Philippines by significantly reducing construction time and material costs while meeting structural safety standards under NSCP.',
                'introduction' => 'The Philippines faces a housing deficit of over 6 million units, disproportionately affecting low-income households. Conventional construction methods are too slow and costly to close this gap. This study examines 3D-printed concrete construction as a disruptive alternative.',
                'methodology' => 'A prototype single-room concrete structure was printed using a locally adapted 3D construction printer with Portland cement-based concrete mix. Compressive strength, thermal performance, and cost-per-square-meter were measured and compared against conventional hollow block construction.',
                'results' => '3D-printed walls achieved compressive strength of 28.4 MPa, exceeding the NSCP minimum of 17.2 MPa for residential structures. Construction time was reduced by 62% compared to conventional methods. Material costs were 24% lower, primarily due to reduced labor and minimal formwork.',
                'discussion' => 'The technology is structurally viable for single-storey residential construction under Philippine building codes. The main adoption barrier is the high initial capital cost of the printing equipment, which necessitates a shared-service or lease model for community deployment.',
                'references' => "Bos, F., Wolfs, R., Ahmed, Z., & Salet, T. (2016). Additive manufacturing of concrete in construction: Potentials and challenges of 3D concrete printing. Virtual and Physical Prototyping, 11(3), 209–225.\nLim, S., Buswell, R. A., Le, T. T., Austin, S. A., Gibb, A. G., & Thorpe, T. (2012). Developments in construction-scale additive manufacturing processes. Automation in Construction, 21, 262–268.\nRushton, J. (2021). 3D printed houses: A construction revolution. Architectural Science Review, 64(2), 89–97.",
                'conclusion' => '3D-printed concrete structures are structurally compliant with Philippine building codes and offer 62% faster construction and 24% material cost savings, presenting a viable pathway to addressing the Philippine housing backlog.',
                'recommendations' => 'DHSUD should pilot 3D-printed housing in resettlement communities. DTI should develop a certification pathway for 3D construction printing operators. Future research should assess seismic performance of 3D-printed structures under Philippine earthquake loading conditions.',
                'keywords' => '3D printing, additive manufacturing, housing construction, NSCP, concrete, Philippines housing',
                'status' => Research::STATUS_REVISION_RDE,
                'revision_notes' => 'The structural analysis section requires comparison with NSCP seismic zone requirements. Please include data from at least three prototype structures rather than a single prototype.',
            ],
            [
                'title' => 'Cybercrime Victimization Among Filipino Youth: Awareness, Vulnerability, and Coping Strategies',
                'college' => 'CCJE',
                'abstract' => 'This descriptive-correlational study measures cybercrime victimization rates, awareness levels, and coping strategies among Filipino youth aged 15–24, and examines whether digital literacy education and parental supervision are significant protective factors.',
                'introduction' => 'The Philippines consistently ranks among the highest globally for social media usage, making its youth population especially exposed to cyber threats including online scams, cyberbullying, and identity theft. This study provides baseline data on victimization prevalence and identifies modifiable risk and protective factors.',
                'methodology' => 'An online survey collected data from 1,200 youth respondents across 6 regions. Measures included the Cybercrime Victimization Scale, Digital Literacy Assessment, and Cyber Awareness Inventory. Binary logistic regression identified significant predictors of victimization.',
                'results' => '64% of respondents reported at least one cybercrime victimization experience in the past year, most commonly online scams (41%) and cyberbullying (38%). Digital literacy (OR=0.52, p<0.001) and parental oversight (OR=0.67, p=0.003) were significant protective factors. Youth with low digital literacy were 1.92 times more likely to be victimized.',
                'discussion' => 'The high victimization rate underscores the urgency of structured cybersecurity education. The protective effect of digital literacy is robust across all cybercrime types, validating investments in school-based digital safety curricula.',
                'references' => "Holt, T. J., & Bossler, A. M. (2014). An assessment of the current state of cybercrime scholarship. Deviant Behavior, 35(1), 20–40.\nKidder, D. (2018). Cybercrime and youth: An emerging field of study. Journal of Youth Studies, 21(4), 455–470.\nLeukfeldt, R., Kleemans, E., & Stol, W. (2017). Cybercriminal networks, social ties, and online forums. British Journal of Criminology, 57(3), 704–722.\nNorton by Symantec. (2022). Norton cyber safety insights report: Philippines. NortonLifeLock.",
                'conclusion' => 'Nearly two-thirds of Filipino youth have experienced cybercrime victimization. Digital literacy is the most modifiable protective factor, underscoring the need for mandatory digital safety education in the K-12 and SHS curricula.',
                'recommendations' => 'DepEd should integrate cybercrime awareness as a mandatory module in Technology and Livelihood Education. PNP Anti-Cybercrime Group should establish youth-accessible reporting channels. Future research should evaluate the effectiveness of specific cybersecurity education interventions.',
                'keywords' => 'cybercrime, youth victimization, digital literacy, online safety, Philippines, cyberbullying',
                'status' => Research::STATUS_APPROVED,
            ],
            [
                'title' => 'Mental Health Literacy and Help-Seeking Behavior Among Filipino College Students',
                'college' => 'CHM',
                'abstract' => 'This cross-sectional study assesses mental health literacy levels and help-seeking intentions among Filipino college students, and examines the role of stigma, cultural factors, and campus mental health resource availability as predictors of whether students seek professional support.',
                'introduction' => 'Mental health disorders are the leading cause of disability among young Filipinos, yet professional help-seeking rates remain critically low. The Mental Health Act of 2018 mandates mental health programs in schools, but implementation is uneven. This study provides evidence to guide campus mental health program design.',
                'methodology' => 'A validated questionnaire package including the Mental Health Literacy Scale, Stigma Scale, and General Help-Seeking Questionnaire was administered to 950 college students across 4 universities. Multivariate logistic regression identified independent predictors of professional help-seeking intention.',
                'results' => 'Only 29% of students with probable mental health conditions indicated intention to seek professional help. Mental health literacy was positively associated with help-seeking (OR=2.14, p<0.001). Personal stigma (OR=0.41, p<0.001) and perceived inaccessibility of services (OR=0.58, p=0.002) were the strongest barriers.',
                'discussion' => 'Low mental health literacy and high internalized stigma form a dual barrier to help-seeking. Campus interventions must address both knowledge deficits and stigma simultaneously to increase service utilization.',
                'references' => "Jorm, A. F. (2012). Mental health literacy: Empowering the community to take action for better mental health. American Psychologist, 67(3), 231–243.\nLi, W., O'Brien, J. E., Snyder, S. M., & Howard, M. O. (2015). Characteristics of internet addiction/pathological internet use in U.S. university students: A qualitative-method investigation. PLOS ONE, 10(2), Article e0117372.\nTorres, J. B., & Taknint, J. T. (2015). Ethnic traumatic stress, acculturative stress, and depression among Latino veterans. Journal of Counseling Psychology, 62(3), 418–428.\nWorld Health Organization. (2022). World mental health report: Transforming mental health for all. WHO Press.",
                'conclusion' => 'Mental health literacy is the strongest modifiable predictor of help-seeking intention, but stigma remains the most formidable barrier. Integrated campus programs addressing both are essential to improving student mental health outcomes.',
                'recommendations' => 'CHED should require mental health literacy modules in all college general education programs. Universities should hire licensed guidance counselors at the ratio mandated by CHED CMO. Future studies should evaluate peer mental health ambassador programs as a stigma-reduction strategy.',
                'keywords' => 'mental health literacy, help-seeking, stigma, college students, Philippines, Mental Health Act',
                'status' => Research::STATUS_PENDING_COLLEGE,
            ],
            [
                'title' => 'Universal Health Care Act Implementation: Policy Analysis and Early Outcomes in Selected LGUs',
                'college' => 'GS',
                'abstract' => 'This policy analysis study evaluates the early implementation of Republic Act 11223, the Universal Health Care Act, in six selected local government units across three regions, examining enrollment coverage, PhilHealth benefit utilization, and primary care facility strengthening outcomes eighteen months post-enactment.',
                'introduction' => 'RA 11223 represents the most comprehensive health financing reform in Philippine history, mandating automatic enrollment of all Filipinos in PhilHealth and reorganizing primary care delivery through the Konsulta Package. Rigorous early evaluation is necessary to identify implementation bottlenecks before they become entrenched.',
                'methodology' => 'A multiple case study design was employed, combining analysis of PhilHealth administrative data, DOH facility assessment reports, and 36 key informant interviews with LGU health officers, PhilHealth regional directors, and RHU physicians across 6 LGUs spanning Luzon, Visayas, and Mindanao.',
                'results' => 'Automatic enrollment increased PhilHealth coverage from 71% to 94% nationally, but Konsulta Package utilization reached only 23% of enrolled members. Primary care facilities in 4 of 6 LGUs lacked accreditation requirements for the Konsulta benefit. Staffing shortfalls and supply chain gaps were the most cited implementation barriers.',
                'discussion' => 'The coverage expansion goal is largely achieved, but service utilization lags due to facility readiness gaps. The transition from volume-based to capitation payment requires significant primary care infrastructure investment that many LGUs cannot finance independently.',
                'references' => "Dayrit, M. M., Lagrada, L. P., Picazo, O. F., Pons, M. C., & Villaverde, M. C. (2018). The Philippines health system review. WHO Regional Office for the Western Pacific.\nFilmer, D., & Lavado, R. (2012). The Philippines: Health financing performance in a period of reform. Health Policy and Planning, 27(5), 415–425.\nRomualdez, A. G., dela Rosa, J. F. E., Flavier, J. D. A., Quimbo, S. L. A., Hartigan-Go, K. Y., Lagrada, L. P., & David, L. C. (2011). The Philippines health system review. WHO Regional Office for South-East Asia.",
                'conclusion' => 'The UHC Act has successfully expanded enrollment coverage but faces critical service utilization gaps due to primary care facility readiness deficits. Targeted infrastructure investment and LGU capacity building are essential to realizing the law\'s intent.',
                'recommendations' => 'DOH should prioritize Konsulta Package facility accreditation support for resource-constrained LGUs. DBM should create a dedicated UHC implementation fund accessible to fourth to sixth class municipalities. PHIC should simplify accreditation requirements for rural health units.',
                'keywords' => 'Universal Health Care Act, PhilHealth, Konsulta Package, policy analysis, primary care, health financing',
                'status' => Research::STATUS_REVISION_COLLEGE,
                'revision_notes' => 'The discussion section needs to engage more critically with comparative international UHC implementation literature. Please also clarify the criteria used for LGU selection to address potential selection bias.',
            ],
            [
                'title' => 'Factors Influencing Research Productivity Among Faculty in Philippine State Universities',
                'college' => 'GS',
                'abstract' => 'This mixed-methods study identifies institutional, motivational, and structural factors that influence research productivity among faculty members in Philippine State Universities and Colleges (SUCs), and proposes a Research Productivity Enhancement Framework tailored to the SUC context.',
                'introduction' => 'Philippine SUCs are mandated to contribute to national development through research, yet per-faculty publication output remains low compared to ASEAN regional peers. Understanding the multilevel factors that enable or constrain faculty research is prerequisite to effective institutional policy.',
                'methodology' => 'Survey data from 480 faculty members across 8 SUCs were analyzed using hierarchical multiple regression. Qualitative data from 32 focus group participants supplemented statistical findings. Variables included research load, funding access, mentoring availability, motivation type, and institutional culture measures.',
                'results' => "Hierarchical regression explained 61% of variance in publication output (R²=0.61, F=28.4, p<0.001). The three strongest predictors were:\n\n| Predictor | Beta | p-value |\n| Dedicated research time allocation | 0.47 | <0.001 |\n| Access to external research funding | 0.39 | <0.001 |\n| Collegial research mentoring | 0.31 | <0.001 |\n\nInstitutional culture of excellence and intrinsic motivation were significant but weaker predictors (β=0.22 and β=0.18 respectively).",
                'discussion' => 'Structural factors—time and funding—outweigh motivational factors as drivers of research productivity. This finding challenges programs focused solely on faculty motivation without addressing systemic resource constraints.',
                'references' => "Bland, C. J., Center, B. A., Finstad, D. A., Risbey, K. R., & Staples, J. G. (2005). A theoretical, practical, predictive model of faculty and department research productivity. Academic Medicine, 80(3), 225–237.\nCasey, D., & Houghton, C. (2010). Clarifying case study research: Examples from practice. Nurse Researcher, 17(3), 41–51.\nPelz, D. C., & Andrews, F. M. (1966). Scientists in organizations: Productive climates for research and development. Wiley.",
                'conclusion' => 'Research time allocation and funding access are the most influential determinants of faculty research productivity in Philippine SUCs. Structural reforms addressing these two factors will yield higher returns than motivation-focused interventions alone.',
                'recommendations' => 'CHED should mandate a minimum 40% research workload credit for SUC faculty with active grants. DOST should streamline grant application processes for first-time grantees. SUCs should establish internal mentoring programs pairing junior and senior researchers.',
                'keywords' => 'research productivity, faculty, state universities, Philippines, higher education, publication output',
                'status' => Research::STATUS_APPROVED,
            ],
        ];

        foreach ($papers as $i => $paper) {
            $college = $colleges->where('code', $paper['college'])->first();
            $student = $students->get($i % $students->count());
            $category = $categories->get($i % $categories->count());

            $status = $paper['status'] ?? Research::STATUS_APPROVED;
            $isApproved = $status === Research::STATUS_APPROVED;

            Research::create([
                'title' => $paper['title'],
                'abstract' => $paper['abstract'],
                'introduction' => $paper['introduction'],
                'methodology' => $paper['methodology'],
                'results' => $paper['results'],
                'discussion' => $paper['discussion'],
                'references' => $paper['references'] ?? null,
                'conclusion' => $paper['conclusion'] ?? null,
                'recommendations' => $paper['recommendations'] ?? null,
                'keywords' => $paper['keywords'] ?? 'research, Philippines',
                'authors' => $student ? $student->name . ', et al.' : 'Unknown Author',
                'college_id' => $college ? $college->id : $colleges->first()->id,
                'category_id' => $category->id,
                'user_id' => $student ? $student->id : User::where('role', 'student')->first()->id,
                'status' => $status,
                'approved_by' => $isApproved ? $approver?->id : null,
                'approved_at' => $isApproved ? now() : null,
                'revision_notes' => $paper['revision_notes'] ?? null,
                'publication_year' => rand(2020, 2025),
            ]);
        }
    }
}
